name: Run Crawler

on: workflow_dispatch

permissions:
  actions: write
  contents: write

concurrency:
  group: "crawling"
  cancel-in-progress: true

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run Crawler
        if: false # At the moment, this is deactivated as the action runs too long.
        run: |
          npm install
          npm run start
          mkdir release
          cp satellites.csv release/
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: List of Satellites ${{ steps.date.outputs.date }}
          workdir: release
